eureka:
        client:
           service-url:
               defaultZone : http://10.20.0.131:8761/eureka/
debug: false
server:
       port: 8990
dubbo:
      application:
              name : erp-service-product-test
      registry:
              protocol : zookeeper
              address : 10.20.0.137:2181
      protocol:
              name : dubbo
              port : 2281
      owner :
              douglas.jiang

spring:
      application:
              name : product-Service
      datasource:
         driver-class-name : com.mysql.jdbc.Driver
         url : jdbc:mysql://10.20.0.141:3306/nearbyexpress?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
         username : eshoponline
         password : Testdb201705
log:
    path:  logs
    level: info
