debug: true
server:
       port: 8081
eureka:
        client:
           service-url:
               defaultZone : http://10.20.0.152:8761/eureka/

spring:
      datasource:
         url : jdbc:mysql://10.20.0.151:3306/dev_nearbyexpress?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
         username : dev_express
         password : Devdb201707
log:
    path:  d://logs
    level: info

#自定义配置
uploadimage :
    windowspath : D:\\upload\\
    linuxpath : /home/pic/public_html/upload/

driver:
     download:
        domain: http://sunvalley.test.com
