debug: true
server:
       port: 8081

spring:
      datasource:
         url : jdbc:mysql://10.20.0.151:3306/dev_nearbyexpress?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
         username : dev_express
         password : Devdb201707
log:
    path:  logs
    level: info




#barker.url:tcp://10.20.0.137:61616
#dubbo.url:zookeeper://10.20.0.137:2181
#sserver.name:ERPBS