eureka:
        client:
           healthcheck:
              enabled: true
           service-url:
               defaultZone : http://10.20.0.152:8761/eureka/
        instance:
            lease-renewal-interval-in-seconds: 3     # 心跳时间，即服务续约间隔时间（缺省为30s）
            lease-expiration-duration-in-seconds: 5  # 发呆时间，即服务续约到期时间（缺省为90s）
            prefer-ip-address: true                  # 使用ip
server:
       tomcat:
         uri-encoding: UTF-8
       port: 8081

spring:
      application:
              name : product-Service
      profiles:
        active: dev
      datasource:
         driver-class-name : com.mysql.jdbc.Driver
         url : jdbc:mysql://10.20.0.151:3306/dev_nearbyexpress?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
         username : dev_express
         password : Devdb201707
         type : com.alibaba.druid.pool.DruidDataSource
         druid:
              initial-size : 20
              min-idle : 1
              max-active : 500
              max-wait : 60000
              time-between-eviction-runs-millis : 60000
              min-evictable-idle-time-millis : 300000
              max-evictable-idle-time-millis : 300000
              validation-query : SELECT 1
              validation-query-timeout : 30000
              test-while-idle : true
              test-on-borrow : false
              test-on-return : false
              pool-prepared-statements : false
              max-pool-prepared-statement-per-connection-size : 20
              max-open-prepared-statements : 20
              filters : stat,slf4j
              filter:
                slf4j:
                  enabled: true
                  statement-executable-sql-log-enable: true
      jackson:
        date-format: "yyyy-MM-dd HH:mm:ss"
        time-zone: "GMT+08"
      http:
        encoding:
          force: true
          charset: utf-8
          enabled: true




mybatis:
     type-aliases-package : com.sunvalley.erp.product.model,com.sunvalley.erp.to
     mapper-locations: classpath*:mapper/com/sunvalley/erp/product/**/*.xml

     #config-location: classpath:/mybatis-config.xml

debug: false

log:
    path:  logs
    level: info

#自定义配置
uploadimage :
    windowspath : D:\\upload\\
    linuxpath : /home/pic/public_html/upload/

driver:
     download:
        domain: http://sunvalley.test.com
