dubbo:
    application:
         name: web-consumerr
    registry:
      address: zookeeper://10.20.0.137:2181
    protocol:
      name: dubbo
      port: 2281
spring:
    dubbo:
        scan: com.sunvalley.controller




#dubbo:application.name=web-consumerr
#dubbo.registry.address=zookeeper://192.168.3.6:2181
#spring.dubbo.scan=com.sunvalley.controller
#dubbo.protocol.name = dubbo
#dubbo.protocol.port = 2281
